name: kedame_gebya
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  http: ^0.13.5

  cupertino_icons: ^1.0.2
  flutter_add_to_cart_button: ^1.1.0
  mobile_number: ^2.1.1
  fluttertoast: ^8.2.1
  sqflite: ^2.2.6
  path_provider: ^2.0.14
  sim_data: ^0.0.2
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - images/baby.jpg
  fonts:
  - family: Pacifico
    fonts:
    - asset: fonts/Pacifico-Regular.ttf

  - family: Sacramento
    fonts:
    - asset: fonts/Sacramento-Regular.ttf